spring:
  datasource:
    url: jdbc:mysql://192.168.100.101:3306/more_testdb1?useSSL=false&serverTimezone=UTC
    username: testuser
    password: Test@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource2:
    url: jdbc:mysql://192.168.100.103:3306/more_tesdb2?useSSL=false&serverTimezone=UTC
    username: testuser
    password: Test@123
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.hf.entity
